<!DOCTYPE php>
<php>
<head>
	<meta http-equiv="content-type" content="text/php; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="cssSlider created with cssSlider, a free wizard program that helps you easily generate beautiful web slideshow" />
    <title>Project Live Vocaloid</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">      
	<meta name="author" content="php5TemplatesDreamweaver.com">
	<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"> <!-- Remove this Robots Meta Tag, to allow indexing of site -->
    
	<?php include('layout/stylesheet.php') ?>    
    <!-- Le php5 shim, for IE6-8 support of php5 elements -->
    <!--[if lt IE 9]>
      <script src="http://php5shim.googlecode.com/svn/trunk/php5.js"></script>
    <![endif]-->

    <!--[if lt IE 8]>
        <link href="scripts/icons/general/stylesheets/general_foundicons_ie7.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="scripts/icons/social/stylesheets/social_foundicons_ie7.css" media="screen" rel="stylesheet" type="text/css" />
    <![endif]-->
    <!--[if IE 7]>
        <link rel="stylesheet" href="scripts/fontawesome/css/font-awesome-ie7.min.css">
    <![endif]-->

</head>
<body id="pageBody">

<div id="decorative2">
    <div class="container">
	<?php include('layout/header.php') ?>    

<div id="decorative1" style="position:relative">
		<!-- Start cssSlider.com -->
		<!-- Generated by cssSlider.com 2.0 -->
		<link rel="stylesheet" href="cssslider_files/csss_engine1/style.css">
		<!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
		<!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
		 <div class="csslider1 autoplay ">
		<input name="cs_anchor1" id="cs_slide1_0" class="cs_anchor slide" type="radio">
		<input name="cs_anchor1" id="cs_slide1_1" class="cs_anchor slide" type="radio">
		<input name="cs_anchor1" id="cs_slide1_2" class="cs_anchor slide" type="radio">
		<input name="cs_anchor1" id="cs_play1" class="cs_anchor" checked="" type="radio">
		<input name="cs_anchor1" id="cs_pause1_0" class="cs_anchor pause" type="radio">
		<input name="cs_anchor1" id="cs_pause1_1" class="cs_anchor pause" type="radio">
		<input name="cs_anchor1" id="cs_pause1_2" class="cs_anchor pause" type="radio">
		<ul>
			<li class="cs_skeleton"><img src="cssslider_files/csss_images1/01.jpg" style="width: 100%;"></li>
			<li class="num0 img slide"> <img src="cssslider_files/csss_images1/01.jpg" alt="01" title="01"></li>
			<li class="num1 img slide"> <img src="cssslider_files/csss_images1/02.jpg" alt="02" title="02"></li>
			<li class="num2 img slide"> <img src="cssslider_files/csss_images1/03.jpg" alt="03" title="03"></li>
		</ul><div class="cs_engine"><a href="http://cssslider.com">responsive slider jquery</a> by cssSlider.com v2.0</div>
		
		
		<div class="cs_arrowprev">
			<label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
			<label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
			<label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
		</div>
		<div class="cs_arrownext">
			<label class="num0" for="cs_slide1_0"><span><i></i><b></b></span></label>
			<label class="num1" for="cs_slide1_1"><span><i></i><b></b></span></label>
			<label class="num2" for="cs_slide1_2"><span><i></i><b></b></span></label>
		</div>
		<div class="cs_bullets">
			<label class="num0" for="cs_slide1_0"> <span class="cs_point"></span>
				</label>
			<label class="num1" for="cs_slide1_1"> <span class="cs_point"></span>
				</label>
			<label class="num2" for="cs_slide1_2"> <span class="cs_point"></span>
				</label>
		</div>
		</div>
		<!-- End cssSlider.com -->
</div>

<div id="contentOuterSeparator"></div>

<div class="container">

    <div class="divPanel page-content">
        <!--Edit Main Content Area here-->
        <div class="row-fluid">

                <div class="span12" id="divMain">

                    <h1>Qui sommes-nous ?</h1>

                    <p><strong>"Project Live Vocaloid"</strong> est une Association ayant pour but premier de promouvoir le phénomène Vocaloid en France via différentes activités et événements. 
                    <br>Nous sommes avant tout des fans de l’univers créatif Vocaloid, et nous souhaitons partager notre passion pour ce phénomène et aider son développement en France. 
                    <br>Notre but premier est l’organisation de concerts amateurs pour rependre le phénomène Vocaloid à travers la France. Nous pensons qu’il est important que la culture Vocaloid soit accessible à tous, et nous sommes là pour cela.</p>

                    <hr style="margin:45px 0 35px" />
					
					<div class="row-fluid">
				
                    <div class="span4">
                        <h4>Evénements</h4>
                        <img src="images/voca img 1.png" class="img-polaroid" style="margin:5px 0px 15px;" alt="">                
                        <p>Nous sommes présents dans de nombreuses conventions ! Venez nous rencontrer et partager un moment de complicité avec les membres.<br /></p>
                        <p><a href="#" class="btn btn-primary" style="margin:5px 0px 15px;">Liste des événements</a></p>
                    </div>
					
                    <div class="span4">                
                        <h4>Nous rejoindre</h4>
                        <img src="images/voca img 2.png" class="img-polaroid" style="margin:5px 0px 15px;" alt="">  
                        <p>Vous voulez participer aux activités de l'association, bénéficier d'avantages membres et rencontrer des fans ? C'est par ici !<br /></p>
                        <p><a href="membres.php" class="btn btn-primary" style="margin:5px 0px 15px;">Devenir membre</a></p>
                    </div>
					
                    <div class="span4">                
                        <h4>Vocaloid ? Qu'est-ce donc ?</h4>
                        <img src="images/voca img 3.png" class="img-polaroid" style="margin:5px 0px 15px;" alt="">  
                        <p>Découvrez l'univers de Vocaloid et des chanteurs virtuels à travers un article clair et soigné rédigé par notre staff !<br /></p>
                        <p><a href="vocaloid-qu-est-ce-donc.php" class="btn btn-primary" style="margin:5px 0px 15px;">Allons voir ça</a></p>
                    </div>
					
			    </div>
				
				    <hr style="margin:45px 0 35px" />

                    <div class="lead">
                        <h1>Ne ratez plus rien de Project Live Vocaloid</h1> 
                        <h3>Tenez vous au courant de nos actualités via nos réseaux sociaux !</h3>
                        
						    <!-- page feed code will be here -->
			<?php include('layout/feedbackFB.php') ?>					
                </div>
            </div>
			<!--End Main Content Area here-->

        <div id="footerInnerSeparator"></div>
    </div>

</div>

<div id="footerOuterSeparator"></div>

			<?php include('layout/footer.php') ?>					
			<?php include('layout/javascript.php') ?>					

</body>
</php>